
#line 3 "lex.GLSL.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE GLSLrestart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE GLSLlex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via GLSLrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void GLSLrestart (FILE *input_file ,yyscan_t yyscanner );
void GLSL_switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE GLSL_create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void GLSL_delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void GLSL_flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void GLSLpush_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void GLSLpop_buffer_state (yyscan_t yyscanner );

static void GLSLensure_buffer_stack (yyscan_t yyscanner );
static void GLSL_load_buffer_state (yyscan_t yyscanner );
static void GLSL_init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER GLSL_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE GLSL_scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE GLSL_scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE GLSL_scan_bytes (yyconst char *bytes,int len ,yyscan_t yyscanner );

void *GLSLalloc (yy_size_t ,yyscan_t yyscanner );
void *GLSLrealloc (void *,yy_size_t ,yyscan_t yyscanner );
void GLSLfree (void * ,yyscan_t yyscanner );

#define yy_new_buffer GLSL_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        GLSLensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            GLSL_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        GLSLensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            GLSL_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 139
#define YY_END_OF_BUFFER 140
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[426] =
    {   0,
        0,    0,  140,  138,  137,  136,   61,  138,  138,   44,
       45,   53,   59,   41,   60,   68,   54,  131,  133,   56,
       52,   48,   29,   49,   55,  135,   46,   47,  138,  135,
      135,  135,  135,  135,  135,  135,  135,  135,  135,  135,
      135,  135,  135,  135,  135,  135,  135,  135,  135,   42,
      138,   43,   62,  137,   67,   36,   63,   39,   32,   57,
       34,   58,   33,  134,   38,  134,  131,    0,    0,    0,
      133,    0,   50,   66,   51,    0,  135,   37,   65,  135,
      135,  135,  135,  135,  135,  135,  135,  135,  135,   80,
      135,  135,  135,  135,  135,  135,  135,  135,  135,  135,

      135,  135,  135,   69,   23,  135,  135,  135,  135,  135,
      135,  135,  135,  135,  135,  135,  135,  135,  135,  135,
      135,  135,  135,  135,  135,  135,  135,  135,  135,  135,
      135,  135,   35,   64,    0,    0,  134,  132,   31,   30,
       82,  135,  135,  135,  135,  135,  135,  135,  135,  135,
      135,  135,  135,  135,  135,  135,  135,  135,  135,   75,
      135,  135,  135,  135,  135,  135,  135,  135,    5,  135,
      135,  135,  135,  135,  135,  135,  135,   24,  135,  135,
      135,  135,  135,  135,  135,  135,  135,  135,  135,  135,
      135,  135,  135,  135,  135,  135,  135,  135,  135,  135,

      135,    0,  134,  135,    9,  135,  135,  128,  135,  135,
      135,  135,  135,  135,  135,   70,   85,  135,  135,  135,
      101,  135,  135,   90,  105,  135,  135,  135,  135,  135,
      135,  135,  135,  102,   26,   13,   14,   15,  135,  135,
      135,  135,  135,  135,  135,  135,  135,  135,  135,  135,
      135,  135,  135,  135,   88,   77,  135,  135,  135,  135,
      135,  135,    2,    3,    4,   16,  135,  135,  135,   72,
       10,   11,   12,   83,   22,  135,  135,  135,  135,  114,
      115,  116,  135,   78,  106,    1,  117,  118,  119,   28,
      111,  112,  113,  135,   25,  109,  135,  135,    6,    7,

        8,  135,  135,  135,  135,  135,  135,  135,  135,  135,
      103,  135,  135,  135,  135,  135,  135,  135,  135,   84,
      135,  130,  135,  135,   81,  135,  135,  135,  135,  104,
       98,   93,  135,  135,  135,  135,  135,  110,   89,  135,
       96,   71,  135,  127,   97,   76,  108,   91,  135,  135,
      135,  135,  135,  135,  135,  135,   92,   73,  135,  135,
      135,   27,  135,  135,  135,  135,  135,   86,   20,  135,
       21,  135,  135,   74,   99,  135,  135,  135,   94,  135,
      135,  135,  135,  135,   87,  107,   95,   19,  100,   79,
      129,   40,  120,   17,  121,  135,  135,  135,  135,  135,

      135,  135,  135,  135,  135,   18,  135,  135,  135,  135,
      135,  124,  135,  125,  135,  135,  135,  122,  135,  123,
      135,  135,  135,  126,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    1,    1,    5,    6,    1,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   28,   29,   30,   31,   28,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   33,   34,   32,   32,   32,   32,   35,   32,   32,
       36,    1,   37,   38,   32,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   32,   48,   49,   50,   51,
       52,   53,   32,   54,   55,   56,   57,   58,   59,   60,
       61,   62,   63,   64,   65,   66,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[67] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    2,    1,    3,    3,    3,    3,    3,    3,
        3,    1,    1,    1,    1,    1,    1,    4,    4,    4,
        3,    5,    5,    5,    5,    1,    1,    1,    4,    4,
        4,    4,    3,    4,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[430] =
    {   0,
        0,    0,  528,  529,  525,  529,  501,  500,   61,  529,
      529,  499,   58,  529,   57,   55,  498,   74,   65,  529,
      529,   55,  497,   59,  529,    0,  529,  529,   63,   42,
       48,   64,   67,   69,   83,  469,   65,   80,  468,   38,
       76,  462,   82,  475,   98,   97,   56,  107,  471,  529,
      101,  529,  529,  514,  529,  529,  529,  529,  529,  529,
      529,  529,  529,  151,  529,  158,   92,  149,  187,    0,
      150,  490,  529,  529,  529,  489,    0,  529,  529,  463,
      456,  459,  467,  466,  453,  468,  455,  461,  449,  446,
      459,  446,  443,  443,  449,  437,  108,  442,  452,  438,

      444,  447,  448,    0,  160,  447,   97,  433,  446,  437,
      439,  429,  443,  440,  442,  425,  430,  427,  416,  110,
      424,  429,  425,  427,  416,  419,  106,  424,  416,  428,
      136,  421,  529,  529,  205,  212,  219,    0,  529,  529,
        0,  413,  417,  426,  423,  407,  407,  131,  422,  419,
      419,  417,  414,  406,  412,  399,  410,  396,  412,    0,
      409,  397,  404,  401,  405,  398,  387,  386,  399,  402,
      399,  394,  385,  224,  390,  393,  384,  381,  385,  391,
      382,  373,  376,  374,  384,  370,  368,  381,  367,  369,
      366,  377,  376,  144,  371,  366,  355,  227,  373,  375,

      364,  232,  239,  365,    0,  363,  244,    0,  355,  353,
      361,  350,  367,  356,  247,    0,    0,  350,  360,  360,
        0,  345,  250,    0,    0,  347,  253,  348,  342,  341,
      342,  341,  256,    0,    0,    0,    0,    0,  337,  338,
      343,  334,  347,  342,  341,  333,  337,  329,  332,  336,
      341,  327,  339,  330,    0,    0,  336,  325,  325,  330,
      329,  326,    0,    0,    0,    0,  316,  328,  330,    0,
        0,    0,    0,    0,    0,  318,  319,  313,  323,    0,
        0,    0,  314,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  321,    0,    0,  319,  315,    0,    0,

        0,  311,  307,  312,  302,  315,  301,  314,  303,  310,
        0,  308,  310,  294,  296,  302,  308,  303,  291,    0,
      293,    0,  292,  295,    0,  284,  283,  283,  296,    0,
      298,    0,  297,  296,  281,  294,  281,    0,    0,  284,
        0,    0,  276,    0,    0,    0,    0,    0,  273,  284,
      277,  283,  280,  275,  267,  279,    0,    0,  272,  279,
      268,    0,  277,  274,  264,  260,  272,    0,    0,  272,
        0,  270,  269,    0,    0,  268,  254,  266,    0,  257,
      277,  276,  275,  247,    0,    0,    0,    0,    0,    0,
        0,    0,  269,  157,  269,  261,  254,  256,  242,  244,

      243,  246,  243,  244,  241,    0,  239,  224,  237,  163,
      162,  177,  158,    0,  141,  152,  136,    0,  145,    0,
      100,   81,   40,    0,  529,  288,  289,  293,  294
    } ;

static yyconst flex_int16_t yy_def[430] =
    {   0,
      425,    1,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  426,  425,
      425,  425,  425,  425,  425,  427,  425,  425,  425,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,   18,  428,  425,  429,
      426,  425,  425,  425,  425,  425,  427,  425,  425,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,

      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  425,  425,  425,  425,  425,  429,  425,  425,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,

      427,  425,  425,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,

      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,

      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,    0,  425,  425,  425,  425
    } ;

static yyconst flex_int16_t yy_nxt[596] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   19,   19,   19,   19,
       19,   20,   21,   22,   23,   24,   25,   26,   26,   26,
       26,   26,   26,   26,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   26,   39,   40,
       41,   42,   43,   44,   45,   46,   47,   48,   49,   26,
       26,   26,   50,   51,   52,   53,   57,   60,   62,   64,
       64,   64,   64,   64,   64,   64,  108,   66,   72,   73,
      109,   63,   61,   75,   76,   58,   66,   78,   67,   67,
       67,   67,   67,   67,   68,   69,   80,   81,  424,   82,

       79,   83,   85,  101,   69,   84,  127,   69,   70,   88,
      128,  102,   86,   89,  110,   87,   69,   92,   90,   93,
      113,   95,  103,  104,   91,  133,  425,  111,   94,   96,
      105,   97,  423,   70,   98,  114,  117,  106,  115,  123,
       99,  422,  124,  118,  119,  129,  158,  172,  186,  130,
      125,  425,  194,  120,  121,  173,  122,  126,  131,  159,
      195,   66,   66,  187,  134,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   69,
       69,  135,  199,  421,  200,  210,  211,  258,  135,  398,
      399,   69,   69,  135,  420,  259,  136,  419,  136,  418,

      135,  137,  137,  137,  137,  137,  137,  137,  166,  417,
      416,  167,  168,  415,  202,  169,  202,  170,  414,  203,
      203,  203,  203,  203,  203,  203,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,
      236,  237,  238,  263,  264,  265,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      271,  272,  273,  280,  281,  282,  287,  288,  289,  291,
      292,  293,  299,  300,  301,  381,  382,  383,  413,  412,
      411,  410,  409,  408,  407,  406,  405,  404,  384,   71,
       71,   77,   77,   77,   68,   68,  138,  138,  403,  402,

      401,  400,  397,  396,  395,  394,  393,  392,  391,  390,
      389,  388,  387,  386,  385,  380,  379,  378,  377,  376,
      375,  374,  373,  372,  371,  370,  369,  368,  367,  366,
      365,  364,  363,  362,  361,  360,  359,  358,  357,  356,
      355,  354,  353,  352,  351,  350,  349,  348,  347,  346,
      345,  344,  343,  342,  341,  340,  339,  338,  337,  336,
      335,  334,  333,  332,  331,  330,  329,  328,  327,  326,
      325,  324,  323,  322,  321,  320,  319,  318,  317,  316,
      315,  314,  313,  312,  311,  310,  309,  308,  307,  306,
      305,  304,  303,  302,  298,  297,  296,  295,  294,  290,

      286,  285,  284,  283,  279,  278,  277,  276,  275,  274,
      270,  269,  268,  267,  266,  262,  261,  260,  257,  256,
      255,  254,  253,  252,  251,  250,  249,  248,  247,  246,
      245,  244,  243,  242,  241,  240,  239,  235,  234,  233,
      232,  231,  230,  229,  228,  227,  226,  225,  224,  223,
      222,  221,  220,  219,  218,  217,  216,  215,  214,  213,
      212,  209,  208,  207,  206,  205,  204,  201,  198,  197,
      196,  193,  192,  191,  190,  189,  188,  185,  184,  183,
      182,  181,  180,  179,  178,  177,  176,  175,  174,  171,
      165,  164,  163,  162,  161,  160,  157,  156,  155,  154,

      153,  152,  151,  150,  149,  148,  147,  146,  145,  144,
      143,  142,  141,  140,  139,   54,  132,  116,  112,  107,
      100,   74,   65,   59,   56,   55,   54,  425,    3,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425

    } ;

static yyconst flex_int16_t yy_chk[596] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    9,   13,   15,   16,
       16,   16,   16,   16,   16,   16,   40,   19,   22,   22,
       40,   15,   13,   24,   24,    9,   18,   29,   18,   18,
       18,   18,   18,   18,   18,   19,   30,   30,  423,   31,

       29,   31,   32,   37,   18,   31,   47,   19,   18,   33,
       47,   37,   32,   33,   41,   32,   18,   34,   33,   34,
       43,   35,   37,   38,   33,   51,   67,   41,   34,   35,
       38,   35,  422,   18,   35,   43,   45,   38,   43,   46,
       35,  421,   46,   45,   45,   48,   97,  107,  120,   48,
       46,   67,  127,   45,   45,  107,   45,   46,   48,   97,
      127,   68,   71,  120,   51,   64,   64,   64,   64,   64,
       64,   64,   66,   66,   66,   66,   66,   66,   66,   68,
       71,   64,  131,  419,  131,  148,  148,  194,   66,  394,
      394,   68,   71,   64,  417,  194,   69,  416,   69,  415,

       66,   69,   69,   69,   69,   69,   69,   69,  105,  413,
      412,  105,  105,  411,  135,  105,  135,  105,  410,  135,
      135,  135,  135,  135,  135,  135,  136,  136,  136,  136,
      136,  136,  136,  137,  137,  137,  137,  137,  137,  137,
      174,  174,  174,  198,  198,  198,  202,  202,  202,  202,
      202,  202,  202,  203,  203,  203,  203,  203,  203,  203,
      207,  207,  207,  215,  215,  215,  223,  223,  223,  227,
      227,  227,  233,  233,  233,  366,  366,  366,  409,  408,
      407,  405,  404,  403,  402,  401,  400,  399,  366,  426,
      426,  427,  427,  427,  428,  428,  429,  429,  398,  397,

      396,  395,  393,  384,  383,  382,  381,  380,  378,  377,
      376,  373,  372,  370,  367,  365,  364,  363,  361,  360,
      359,  356,  355,  354,  353,  352,  351,  350,  349,  343,
      340,  337,  336,  335,  334,  333,  331,  329,  328,  327,
      326,  324,  323,  321,  319,  318,  317,  316,  315,  314,
      313,  312,  310,  309,  308,  307,  306,  305,  304,  303,
      302,  298,  297,  294,  283,  279,  278,  277,  276,  269,
      268,  267,  262,  261,  260,  259,  258,  257,  254,  253,
      252,  251,  250,  249,  248,  247,  246,  245,  244,  243,
      242,  241,  240,  239,  232,  231,  230,  229,  228,  226,

      222,  220,  219,  218,  214,  213,  212,  211,  210,  209,
      206,  204,  201,  200,  199,  197,  196,  195,  193,  192,
      191,  190,  189,  188,  187,  186,  185,  184,  183,  182,
      181,  180,  179,  178,  177,  176,  175,  173,  172,  171,
      170,  169,  168,  167,  166,  165,  164,  163,  162,  161,
      159,  158,  157,  156,  155,  154,  153,  152,  151,  150,
      149,  147,  146,  145,  144,  143,  142,  132,  130,  129,
      128,  126,  125,  124,  123,  122,  121,  119,  118,  117,
      116,  115,  114,  113,  112,  111,  110,  109,  108,  106,
      103,  102,  101,  100,   99,   98,   96,   95,   94,   93,

       92,   91,   90,   89,   88,   87,   86,   85,   84,   83,
       82,   81,   80,   76,   72,   54,   49,   44,   42,   39,
       36,   23,   17,   12,    8,    7,    5,    3,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425

    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[140] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 
        };

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "GLSL.l"
#line 2 "GLSL.l"
//--------------------------------------------------------------
//
// Microsoft Edge Implementation
// Copyright(c) Microsoft Corporation
// All rights reserved.
//
// MIT License
//
// Permission is hereby granted, free of charge, to any person obtaining
// a copy of this software and associated documentation files(the ""Software""),
// to deal in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and / or sell copies
// of the Software, and to permit persons to whom the Software is furnished to do so,
// subject to the following conditions :
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
// INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
// FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE AUTHORS
// OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF
// OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
//--------------------------------------------------------------

#include <stdlib.h>
#include <io.h>

#define fileno _fileno
#define isatty _isatty

class CGLSLParser;

#include "ParseTreeNode.hxx"        /* Tree node is defined here */
#include "GLSL.tab.h"               /* Bison output has token definitions */
#include "GLSLParserGlobals.hxx"    /* This is where we define yyerror, GLSLwrap etc */

#pragma warning(disable:4242 4100 4244 4018 4127 4505)

#line 748 "lex.GLSL.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#define YY_EXTRA_TYPE CGLSLParser*

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    YYLTYPE * yylloc_r;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
    #    define yylloc yyg->yylloc_r
    
int GLSLlex_init (yyscan_t* scanner);

int GLSLlex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int GLSLlex_destroy (yyscan_t yyscanner );

int GLSLget_debug (yyscan_t yyscanner );

void GLSLset_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE GLSLget_extra (yyscan_t yyscanner );

void GLSLset_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *GLSLget_in (yyscan_t yyscanner );

void GLSLset_in  (FILE * in_str ,yyscan_t yyscanner );

FILE *GLSLget_out (yyscan_t yyscanner );

void GLSLset_out  (FILE * out_str ,yyscan_t yyscanner );

int GLSLget_leng (yyscan_t yyscanner );

char *GLSLget_text (yyscan_t yyscanner );

int GLSLget_lineno (yyscan_t yyscanner );

void GLSLset_lineno (int line_number ,yyscan_t yyscanner );

YYSTYPE * GLSLget_lval (yyscan_t yyscanner );

void GLSLset_lval (YYSTYPE * yylval_param ,yyscan_t yyscanner );

       YYLTYPE *GLSLget_lloc (yyscan_t yyscanner );
    
        void GLSLset_lloc (YYLTYPE * yylloc_param ,yyscan_t yyscanner );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int GLSLwrap (yyscan_t yyscanner );
#else
extern int GLSLwrap (yyscan_t yyscanner );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  ,yyscan_t yyscanner);
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int GLSLlex \
               (YYSTYPE * yylval_param,YYLTYPE * yylloc_param ,yyscan_t yyscanner);

#define YY_DECL int GLSLlex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

#line 42 "GLSL.l"


#line 990 "lex.GLSL.c"

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			GLSLensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				GLSL_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		GLSL_load_buffer_state(yyscanner );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 426 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 529 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 44 "GLSL.l"
{ yylval->iType = FLOAT_TOK; return FLOAT_TOK; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 45 "GLSL.l"
{ yylval->iType = VEC2; return VEC2; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 46 "GLSL.l"
{ yylval->iType = VEC3; return VEC3; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 47 "GLSL.l"
{ yylval->iType = VEC4; return VEC4; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 48 "GLSL.l"
{ yylval->iType = INT_TOK; return INT_TOK; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 49 "GLSL.l"
{ yylval->iType = IVEC2_TOK; return IVEC2_TOK; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 50 "GLSL.l"
{ yylval->iType = IVEC3_TOK; return IVEC3_TOK; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 51 "GLSL.l"
{ yylval->iType = IVEC4_TOK; return IVEC4_TOK; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 52 "GLSL.l"
{ yylval->iType = BOOL_TOK; return BOOL_TOK; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 53 "GLSL.l"
{ yylval->iType = BVEC2_TOK; return BVEC2_TOK; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 54 "GLSL.l"
{ yylval->iType = BVEC3_TOK; return BVEC3_TOK; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 55 "GLSL.l"
{ yylval->iType = BVEC4_TOK; return BVEC4_TOK; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 56 "GLSL.l"
{ yylval->iType = MAT2_TOK; return MAT2_TOK; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 57 "GLSL.l"
{ yylval->iType = MAT3_TOK; return MAT3_TOK; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 58 "GLSL.l"
{ yylval->iType = MAT4_TOK; return MAT4_TOK; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 59 "GLSL.l"
{ yylval->iType = VOID_TOK; return VOID_TOK; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 60 "GLSL.l"
{ yylval->iType = SAMPLER2D; return SAMPLER2D; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 61 "GLSL.l"
{ yylval->iType = SAMPLERCUBE; return SAMPLERCUBE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 62 "GLSL.l"
{ yylval->iType = ATTRIBUTE; return ATTRIBUTE; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 63 "GLSL.l"
{ yylval->iType = UNIFORM; return UNIFORM; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 64 "GLSL.l"
{ yylval->iType = VARYING; return VARYING; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 65 "GLSL.l"
{ yylval->iType = CONST_TOK; return CONST_TOK; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 66 "GLSL.l"
{ yylval->iType = IN_TOK; return IN_TOK; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 67 "GLSL.l"
{ yylval->iType = OUT_TOK; return OUT_TOK; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 68 "GLSL.l"
{ yylval->iType = INOUT_TOK; return INOUT_TOK; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 69 "GLSL.l"
{ yylval->iType = LOW_PRECISION; return LOW_PRECISION; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 70 "GLSL.l"
{ yylval->iType = MEDIUM_PRECISION; return MEDIUM_PRECISION; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 71 "GLSL.l"
{ yylval->iType = HIGH_PRECISION; return HIGH_PRECISION; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 72 "GLSL.l"
{ yylval->iType = EQUAL; return EQUAL; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 73 "GLSL.l"
{ yylval->iType = RIGHT_ASSIGN; return RIGHT_ASSIGN; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 74 "GLSL.l"
{ yylval->iType = LEFT_ASSIGN; return LEFT_ASSIGN; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 75 "GLSL.l"
{ yylval->iType = MUL_ASSIGN; return MUL_ASSIGN; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 76 "GLSL.l"
{ yylval->iType = SUB_ASSIGN; return SUB_ASSIGN; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 77 "GLSL.l"
{ yylval->iType = ADD_ASSIGN; return ADD_ASSIGN; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 78 "GLSL.l"
{ yylval->iType = OR_ASSIGN ; return OR_ASSIGN ; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 79 "GLSL.l"
{ yylval->iType = MOD_ASSIGN; return MOD_ASSIGN; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 80 "GLSL.l"
{ yylval->iType = XOR_ASSIGN; return XOR_ASSIGN; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 81 "GLSL.l"
{ yylval->iType = DIV_ASSIGN; return DIV_ASSIGN; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 82 "GLSL.l"
{ yylval->iType = AND_ASSIGN; return AND_ASSIGN; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 83 "GLSL.l"
{ return PRECISION; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 84 "GLSL.l"
{ return COMMA; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 85 "GLSL.l"
{ return LEFT_BRACE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 86 "GLSL.l"
{ return RIGHT_BRACE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 87 "GLSL.l"
{ return LEFT_PAREN; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 88 "GLSL.l"
{ return RIGHT_PAREN; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 89 "GLSL.l"
{ return LEFT_BRACKET; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 90 "GLSL.l"
{ return RIGHT_BRACKET; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 91 "GLSL.l"
{ yylval->iType = LEFT_ANGLE; return LEFT_ANGLE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 92 "GLSL.l"
{ yylval->iType = RIGHT_ANGLE; return RIGHT_ANGLE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 93 "GLSL.l"
{ yylval->iType = LE_OP; return LE_OP; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 94 "GLSL.l"
{ yylval->iType = GE_OP; return GE_OP; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 95 "GLSL.l"
{ return SEMICOLON; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 96 "GLSL.l"
{ return STAR; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 97 "GLSL.l"
{ return SLASH; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 98 "GLSL.l"
{ return QUESTION; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 99 "GLSL.l"
{ return COLON; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 100 "GLSL.l"
{ return INC_OP; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 101 "GLSL.l"
{ return DEC_OP; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 102 "GLSL.l"
{ yylval->iType = PLUS; return PLUS; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 103 "GLSL.l"
{ yylval->iType = DASH; return DASH; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 104 "GLSL.l"
{ yylval->iType = BANG; return BANG; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 105 "GLSL.l"
{ yylval->iType = TILDE; return TILDE; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 106 "GLSL.l"
{ yylval->iType = AND_OP; return AND_OP; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 107 "GLSL.l"
{ yylval->iType = OR_OP; return OR_OP; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 108 "GLSL.l"
{ yylval->iType = XOR_OP; return XOR_OP; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 109 "GLSL.l"
{ return EQ_OP; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 110 "GLSL.l"
{ return NE_OP; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 111 "GLSL.l"
{ return DOT; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 112 "GLSL.l"
{ return IF_TOK; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 113 "GLSL.l"
{ return ELSE_TOK; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 114 "GLSL.l"
{ return RETURN_TOK; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 115 "GLSL.l"
{ return BREAK_TOK; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 116 "GLSL.l"
{ return DISCARD_TOK; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 117 "GLSL.l"
{ return CONTINUE_TOK; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 118 "GLSL.l"
{ return FOR_TOK; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 119 "GLSL.l"
{ return STRUCT_TOK; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 121 "GLSL.l"
{ yylval->fConstant = true; return TRUE_TOK; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 122 "GLSL.l"
{ yylval->fConstant = false; return FALSE_TOK; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 124 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 125 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 126 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 127 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 128 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 129 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 130 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 131 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 132 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 133 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 134 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 135 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 136 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 137 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 138 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 139 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 140 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 141 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 142 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 143 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 144 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 145 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 146 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 147 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 148 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 149 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 150 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 151 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 152 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 153 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 154 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 155 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 156 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 157 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 158 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 159 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 160 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 161 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 162 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 163 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 164 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 165 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 166 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 167 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 168 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 169 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 170 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 171 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 172 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 173 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 174 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 175 "GLSL.l"
{ return UNSUPPORTED_TOKEN; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 177 "GLSL.l"
{ yylval->iIntConstant = ::strtol(yytext, nullptr, 8); return INTCONSTANT; }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 178 "GLSL.l"
{ yylval->iIntConstant = ::strtol(yytext, nullptr, 16); return INTCONSTANT; }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 179 "GLSL.l"
{ yylval->iIntConstant = ::atoi(yytext); return INTCONSTANT; }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 180 "GLSL.l"
{ yylval->doubleConstant = ::atof(yytext); return DOUBLECONSTANT; }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 182 "GLSL.l"
{ if (FAILED(GLSLEnsureSymbolIndex(yyextra, yytext, &yylval->iSymbolIndex))) { GLSLerror(yylloc, yyscanner, "Internal compiler error"); } return IDENTIFIER; }
	YY_BREAK
case 136:
/* rule 136 can match eol */
YY_RULE_SETUP
#line 183 "GLSL.l"
{ GLSLRecordNewline(yyextra); }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 184 "GLSL.l"
;
	YY_BREAK

/* The proprocessor should have removed all invalid characters already */

case 138:
YY_RULE_SETUP
#line 189 "GLSL.l"
{ GLSLerror(yylloc, yyscanner, "Invalid character"); }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 191 "GLSL.l"
ECHO;
	YY_BREAK
#line 1788 "lex.GLSL.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * GLSLlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( GLSLwrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of GLSLlex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = yyg->yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					GLSLrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			GLSLrestart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) GLSLrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 426 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	register char *yy_cp = yyg->yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 426 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 425);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp , yyscan_t yyscanner)
{
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yy_cp = yyg->yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yyg->yy_hold_char;

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yyg->yy_n_chars + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	yyg->yytext_ptr = yy_bp;
	yyg->yy_hold_char = *yy_cp;
	yyg->yy_c_buf_p = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					GLSLrestart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( GLSLwrap(yyscanner ) )
						return EOF;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	if ( c == '\n' )
		   
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void GLSLrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        GLSLensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            GLSL_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	GLSL_init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	GLSL_load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void GLSL_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		GLSLpop_buffer_state();
	 *		GLSLpush_buffer_state(new_buffer);
     */
	GLSLensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	GLSL_load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (GLSLwrap()) processing, but the only time this flag
	 * is looked at is after GLSLwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void GLSL_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE GLSL_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) GLSLalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in GLSL_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) GLSLalloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in GLSL_create_buffer()" );

	b->yy_is_our_buffer = 1;

	GLSL_init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with GLSL_create_buffer()
 * @param yyscanner The scanner object.
 */
    void GLSL_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		GLSLfree((void *) b->yy_ch_buf ,yyscanner );

	GLSLfree((void *) b ,yyscanner );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a GLSLrestart() or at EOF.
 */
    static void GLSL_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	GLSL_flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then GLSL_init_buffer was _probably_
     * called from GLSLrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void GLSL_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		GLSL_load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void GLSLpush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	GLSLensure_buffer_stack(yyscanner);

	/* This block is copied from GLSL_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from GLSL_switch_to_buffer. */
	GLSL_load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void GLSLpop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	GLSL_delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		GLSL_load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void GLSLensure_buffer_stack (yyscan_t yyscanner)
{
	int num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)GLSLalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in GLSLensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)GLSLrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in GLSLensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE GLSL_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) GLSLalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in GLSL_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	GLSL_switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to GLSLlex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       GLSL_scan_bytes() instead.
 */
YY_BUFFER_STATE GLSL_scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return GLSL_scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to GLSLlex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE GLSL_scan_bytes  (yyconst char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) GLSLalloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in GLSL_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = GLSL_scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in GLSL_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE GLSLget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int GLSLget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int GLSLget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *GLSLget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *GLSLget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int GLSLget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *GLSLget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void GLSLset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void GLSLset_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "GLSLset_lineno called with no buffer" , yyscanner); 
    
    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void GLSLset_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "GLSLset_column called with no buffer" , yyscanner); 
    
    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see GLSL_switch_to_buffer
 */
void GLSLset_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void GLSLset_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int GLSLget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void GLSLset_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * GLSLget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void GLSLset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

YYLTYPE *GLSLget_lloc  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylloc;
}
    
void GLSLset_lloc (YYLTYPE *  yylloc_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylloc = yylloc_param;
}
    
/* User-visible API */

/* GLSLlex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int GLSLlex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) GLSLalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* GLSLlex_init_extra has the same functionality as GLSLlex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to GLSLalloc in
 * the yyextra field.
 */

int GLSLlex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    GLSLset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) GLSLalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    GLSLset_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from GLSLlex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * GLSLlex_init()
     */
    return 0;
}

/* GLSLlex_destroy is for both reentrant and non-reentrant scanners. */
int GLSLlex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		GLSL_delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		GLSLpop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	GLSLfree(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        GLSLfree(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * GLSLlex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    GLSLfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *GLSLalloc (yy_size_t  size , yyscan_t yyscanner)
{
	return (void *) malloc( size );
}

void *GLSLrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void GLSLfree (void * ptr , yyscan_t yyscanner)
{
	free( (char *) ptr );	/* see GLSLrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 191 "GLSL.l"



